version: "3.9"
services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=pesquisa_satisfacao

  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb-db
    ports:
      - "27017:27017"

  nodejs:
    build:
      context: ./nodejs
    container_name: nodejs-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
networks:
  default:
    name: pesquisa_network